[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "plant-disease-hierarchical"
version = "0.1.0"
description = "Hierarchical classification of plant leaf diseases (PlantVillage)"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Marija Tadic", email = "svetlanatadic05@gmail.com" }]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
target-version = "py310"
